In [1]:
import numpy as np

#Creation of numpy array : 
    Numpy arrays are created using the three ways. 

In [4]:
#One dimensional
array_1d = np.array([1,2,3,4,5])

In [5]:
print(array_1d)

[1 2 3 4 5]


In [6]:
#two dimensional
array_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#3 dimensional
array_3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [9]:
print(array_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [11]:
#zero dimensional 
array_0d = np.array(40)

In [12]:
print(array_0d)

40


In [21]:
#1d array with arange method
array_a_1d = np.arange(10)

In [20]:
print(array_a_1d)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
#creation of a two dimensional 
array_a_2d = np.arange(10).reshape(2,5)
print(array_a_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
#creation of a two dimensional 
array_a_3d = np.arange(12).reshape(2,2,3)
print(array_a_3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [29]:
#4d array 
array_a_4d = np.arange(48).reshape(2,3,4,2)
print(array_a_4d)

[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]
   [12 13]
   [14 15]]

  [[16 17]
   [18 19]
   [20 21]
   [22 23]]]


 [[[24 25]
   [26 27]
   [28 29]
   [30 31]]

  [[32 33]
   [34 35]
   [36 37]
   [38 39]]

  [[40 41]
   [42 43]
   [44 45]
   [46 47]]]]


In [34]:
#using np.linspace to create 1d array
array_linspace_1d = np.linspace(100,150,10)
print(array_linspace_1d)
#using np.linspace to create 2d array
array_linspace_2d = np.linspace(100,150,10).reshape(2,5)
print(array_linspace_2d)

[100.         105.55555556 111.11111111 116.66666667 122.22222222
 127.77777778 133.33333333 138.88888889 144.44444444 150.        ]
[[100.         105.55555556 111.11111111 116.66666667 122.22222222]
 [127.77777778 133.33333333 138.88888889 144.44444444 150.        ]]


In [43]:

arr_zero_1d = np.zeros(10)
print(arr_zero_1d)

arr_zero_2d = np.zeros(10).reshape(2,5)
print(arr_zero_2d)

arr_ones_1d = np.ones(10)
print(arr_ones_1d)

arr_one_2d = np.ones(10).reshape(2,5)
print(arr_one_2d)

arr_id_1d = np.identity(2)
print(arr_id_1d)

arr_id_2d = np.identity(10).reshape(10,10)
print(arr_id_2d)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
